apiVersion: v1
kind: Service
metadata:
  labels:
    au: "0223092"
  name: {{.Values.name}}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{.Values.name}}
  type: ClusterIP  
